agents:
  queue: macos-14

steps:
  - name: 'Append Unity 2020 Basic Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unity.2020.yml

  - name: 'Append Unity 2021 Basic Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unity.2021.yml

  - label: Conditionally trigger full set of tests
    timeout_in_minutes: 30
    command: sh -c .buildkite/pipeline_trigger.sh
