agents:
  queue: opensource

steps:
  - name: 'Append Unity 2020 Full Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unity.2020.full.yml

  - name: 'Append Unity 2021 Full Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unity.2021.full.yml

  - name: 'Append Unity 2022 Full Pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/unity.2022.full.yml
