aliases:
  - &2020 "2020.3.48f1"
  - &2021 "2021.3.36f1"
  - &2022 "2022.3.22f1"

agents:
  queue: macos-14

steps:
  - label: Build released library artifact
    timeout_in_minutes: 30
    key: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2020
    commands:
      - bundle install
      - 'bundle exec rake plugin:build:export'
    artifact_paths:
      - upm-package.zip
    retry:
      automatic:
        - exit_status: '*'
          limit: 1


  - label: 'build size impact reporting'
    timeout_in_minutes: 10
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
    commands:
      features/scripts/do_size_test.sh

  - label: ':webgl: Build webgl test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-webgl-fixture-2021
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/mazerunner/mazerunner_webgl_2021.zip
          - features/fixtures/build_webgl.log
    commands:
      - bundle install
      - 'rake test:webgl:build'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: Run WebGL e2e tests for Unity 2021
    timeout_in_minutes: 60
    depends_on: build-webgl-fixture-2021
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.5.0':
        download:
          - features/fixtures/mazerunner/mazerunner_webgl_2021.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - 'clear_cache.log'
          - maze_output/metrics.csv
    commands:
      - features/scripts/run-webgl-ci-tests.sh release

  - label: ':webgl: Build webgl DEV test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-webgl-dev-fixture-2021
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/mazerunner/mazerunner_webgl_dev_2021.zip
          - features/fixtures/build_webgl.log
    commands:
      - bundle install
      - 'rake test:webgl:build_dev'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1
          
  - label: Run WebGL DEV e2e tests for Unity 2021
    timeout_in_minutes: 60
    depends_on: build-webgl-dev-fixture-2021
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.5.0':
        download:
          - features/fixtures/mazerunner/mazerunner_webgl_dev_2021.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - 'clear_cache.log'
          - maze_output/metrics.csv
    commands:
      - features/scripts/run-webgl-ci-tests.sh dev


  - label: ':windows: Build Windows test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-windows-fixture-2021
    depends_on: build-artifacts
    agents:
      queue: windows-unity-wsl
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/mazerunner/build/Windows-2021.zip
          - features/fixtures/build_windows.log
    commands:
      - features/scripts/import_package.sh
      - features/scripts/build_windows.sh
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: Run Windows e2e tests for Unity 2021
    timeout_in_minutes: 60
    depends_on: build-windows-fixture-2021
    agents:
      queue: windows-unity-wsl
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.5.0':
        download:
          - features/fixtures/mazerunner/build/Windows-2021.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - 'clear_cache.log'
          - maze_output/metrics.csv
    commands:
      - features/scripts/run-windows-ci-tests.sh

  - label: ':windows: Build Windows DEV test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-windows-dev-fixture-2021
    depends_on: build-artifacts
    agents:
      queue: windows-unity-wsl
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/mazerunner/build/Windows-dev-2021.zip
          - features/fixtures/build_windows.log
    commands:
      - features/scripts/import_package.sh
      - features/scripts/build_windows_dev.sh
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: Run Windows DEV e2e tests for Unity 2021
    timeout_in_minutes: 60
    depends_on: build-windows-dev-fixture-2021
    agents:
      queue: windows-unity-wsl
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.5.0':
        download:
          - features/fixtures/mazerunner/build/Windows-dev-2021.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - 'clear_cache.log'
          - maze_output/metrics.csv
    commands:
      - features/scripts/run-windows-ci-tests-dev.sh


  - label: ':macos: Build macos test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-macos-fixture-2021
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/mazerunner/mazerunner_macos_2021.zip
          - features/fixtures/build_macos.log
    commands:
      - bundle install
      - 'rake test:macos:build'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: Run MacOS e2e tests for Unity 2021
    timeout_in_minutes: 60
    depends_on: build-macos-fixture-2021
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.5.0':
        download:
          - features/fixtures/mazerunner/mazerunner_macos_2021.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - 'clear_cache.log'
          - maze_output/metrics.csv
    commands:
      - features/scripts/run-macos-ci-tests.sh release

  - label: ':macos: Build macos DEV test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-macos-dev-fixture-2021
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/mazerunner/mazerunner_macos_dev_2021.zip
          - features/fixtures/build_macos.log
    commands:
      - bundle install
      - 'rake test:macos:build_dev'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: Run MacOS DEV e2e tests for Unity 2021
    timeout_in_minutes: 60
    depends_on: build-macos-dev-fixture-2021
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.5.0':
        download:
          - features/fixtures/mazerunner/mazerunner_macos_dev_2021.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - 'clear_cache.log'
          - maze_output/metrics.csv
    commands:
      - features/scripts/run-macos-ci-tests.sh dev

  - label: ':android: Build Android test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-android-fixture-2021
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/mazerunner/mazerunner_2021.apk
          - features/fixtures/import_package.log
          - features/fixtures/build_android.log
    commands:
      - bundle install
      - 'rake test:android:build'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: ':android: Build Android Dev test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-android-dev-fixture-2021
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/mazerunner/mazerunner-dev_2021.apk
          - features/fixtures/import_package.log
          - features/fixtures/build_android_dev.log
    commands:
      - bundle install
      - 'rake test:android:build_dev'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: ':bitbar: Run Android DEV e2e tests for Unity 2021'
    timeout_in_minutes: 60
    depends_on: build-android-dev-fixture-2021
    agents:
      queue: opensource
    plugins:
      'artifacts#v1.9.0':
        download:
          - features/fixtures/mazerunner/mazerunner-dev_2021.apk
        upload:
          - maze_output/**/*
      'docker-compose#v4.8.0':
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - '--app=/app/features/fixtures/mazerunner/mazerunner-dev_2021.apk'
          - '--farm=bb'
          - '--device=ANDROID_9|ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13'
          - '--no-tunnel'
          - '--aws-public-ip'
          - '--fail-fast'
    concurrency: 25
    concurrency_group: bitbar
    concurrency_method: eager

  - label: ':bitbar: Run Android e2e tests for Unity 2021'
    timeout_in_minutes: 60
    depends_on: build-android-fixture-2021
    agents:
      queue: opensource
    plugins:
      'artifacts#v1.9.0':
        download:
          - features/fixtures/mazerunner/mazerunner_2021.apk
        upload:
          - maze_output/**/*
      'docker-compose#v4.8.0':
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - '--app=/app/features/fixtures/mazerunner/mazerunner_2021.apk'
          - '--farm=bb'
          - '--device=ANDROID_9|ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13'
          - '--no-tunnel'
          - '--aws-public-ip'
          - '--fail-fast'
    concurrency: 25
    concurrency_group: bitbar
    concurrency_method: eager

  - label: ':ios: Generate Xcode project - Unity 2021'
    timeout_in_minutes: 30
    key: generate-fixture-project-2021
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/generateXcodeProject.log
          - project_2021.tgz
    commands:
      - bundle install
      - 'rake test:ios:generate_xcode'
      - tar -zvcf project_2021.tgz features/fixtures/mazerunner/mazerunner_xcode
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: ':ios: Build iOS test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-ios-fixture-2021
    depends_on: generate-fixture-project-2021
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - project_2021.tgz
        upload:
          - features/fixtures/mazerunner/mazerunner_2021.ipa
          - features/fixtures/unity.log
    commands:
      - bundle install
      - tar -zxf project_2021.tgz features/fixtures/mazerunner
      - 'rake test:ios:build_xcode'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: ':bitbar: Run iOS e2e tests for Unity 2021'
    timeout_in_minutes: 60
    depends_on: build-ios-fixture-2021
    agents:
      queue: opensource
    plugins:
      'artifacts#v1.9.0':
        download:
          - features/fixtures/mazerunner/mazerunner_2021.ipa
        upload:
          - maze_output/**/*
      'docker-compose#v4.8.0':
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - '--app=/app/features/fixtures/mazerunner/mazerunner_2021.ipa'
          - '--farm=bb'
          - '--device=IOS_15'
          - '--no-tunnel'
          - '--aws-public-ip'
          - '--fail-fast'
    concurrency: 25
    concurrency_group: bitbar
    concurrency_method: eager

  - label: ':ios: Generate Xcode DEV project - Unity 2021'
    timeout_in_minutes: 30
    key: generate-dev-fixture-project-2021
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/generateXcodeProject.log
          - dev_project_2021.tgz
    commands:
      - bundle install
      - 'rake test:ios:generate_xcode_dev'
      - tar -zvcf dev_project_2021.tgz features/fixtures/mazerunner/mazerunner_dev_xcode
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: ':ios: Build iOS DEV test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-ios-dev-fixture-2021
    depends_on: generate-dev-fixture-project-2021
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - dev_project_2021.tgz
        upload:
          - features/fixtures/mazerunner/mazerunner_dev_2021.ipa
          - features/fixtures/unity.log
    commands:
      - bundle install
      - tar -zxf dev_project_2021.tgz features/fixtures/mazerunner
      - 'rake test:ios:build_xcode_dev'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: ':bitbar: Run iOS DEV e2e tests for Unity 2021'
    timeout_in_minutes: 60
    depends_on: build-ios-dev-fixture-2021
    agents:
      queue: opensource
    plugins:
      'artifacts#v1.9.0':
        download:
          - features/fixtures/mazerunner/mazerunner_dev_2021.ipa
        upload:
          - maze_output/**/*
      'docker-compose#v4.8.0':
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - '--app=/app/features/fixtures/mazerunner/mazerunner_dev_2021.ipa'
          - '--farm=bb'
          - '--device=IOS_15'
          - '--no-tunnel'
          - '--aws-public-ip'
          - '--fail-fast'
    concurrency: 25
    concurrency_group: bitbar
    concurrency_method: eager

  - label: Conditionally trigger full set of tests
    timeout_in_minutes: 30
    command: sh -c .buildkite/pipeline_trigger.sh
