agents:
  queue: macos

steps:
  - label: 'Append Unity 2020 Full Pipeline'
    timeout_in_minutes: 2
    commands:
      - buildkite-agent pipeline upload .buildkite/unity.2020.full.yml

  # - label: 'Append Unity 2021 Full Pipeline'
  #   timeout_in_minutes: 2
  #   commands:
  #     - buildkite-agent pipeline upload .buildkite/unity.2021.full.yml

  - label: 'Append Unity 2022 Full Pipeline'
    timeout_in_minutes: 2
    commands:
      - buildkite-agent pipeline upload .buildkite/unity.2022.full.yml

  - label: 'Append Unity 6000 Full Pipeline'
    timeout_in_minutes: 2
    commands:
      - buildkite-agent pipeline upload .buildkite/unity.6000.full.yml

