aliases:
  - &2020 "2020.3.48f1"
  - &2021 "2021.3.36f1"
  - &2022 "2022.3.22f1"

agents:
  queue: macos-14

steps:
  - label: Build released library artifact
    timeout_in_minutes: 30
    key: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2020
    commands:
      - bundle install
      - 'bundle exec rake plugin:build:export'
    artifact_paths:
      - upm-package.zip
    retry:
      automatic:
        - exit_status: '*'
          limit: 1


  - label: 'build size impact reporting'
    timeout_in_minutes: 10
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
    commands:
      features/scripts/do_size_test.sh

  - label: ':webgl: Build webgl test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: build-webgl-fixture-2021
    depends_on: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - upm-package.zip
        upload:
          - features/fixtures/mazerunner/mazerunner_webgl_2021.zip
          - features/fixtures/build_webgl.log
    commands:
      - bundle install
      - 'rake test:webgl:build'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - label: Run WebGL e2e tests for Unity 2021
    timeout_in_minutes: 60
    depends_on: build-webgl-fixture-2021
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.5.0':
        download:
          - features/fixtures/mazerunner/mazerunner_webgl_2021.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - 'clear_cache.log'
          - maze_output/metrics.csv
    commands:
      - features/scripts/run-webgl-ci-tests.sh

  - label: Run WebGL e2e tests for Unity 2021
    timeout_in_minutes: 60
    depends_on: build-webgl-fixture-2021
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.5.0':
        download:
          - features/fixtures/mazerunner/mazerunner_webgl_2021.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - 'clear_cache.log'
          - maze_output/metrics.csv
    commands:
      - features/scripts/run-webgl-ci-tests.sh

  - label: Run WebGL e2e tests for Unity 2021
    timeout_in_minutes: 60
    depends_on: build-webgl-fixture-2021
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.5.0':
        download:
          - features/fixtures/mazerunner/mazerunner_webgl_2021.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - 'clear_cache.log'
          - maze_output/metrics.csv
    commands:
      - features/scripts/run-webgl-ci-tests.sh

  - label: Run WebGL e2e tests for Unity 2021
    timeout_in_minutes: 60
    depends_on: build-webgl-fixture-2021
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      'artifacts#v1.5.0':
        download:
          - features/fixtures/mazerunner/mazerunner_webgl_2021.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - 'clear_cache.log'
          - maze_output/metrics.csv
    commands:
      - features/scripts/run-webgl-ci-tests.sh
