aliases:
  - &2021 "2021.3.45f1"
  - &2020 "2020.3.48f1"

agents:
  queue: macos-14-isolated

steps:
  - label: Verify code formatting
    timeout_in_minutes: 5
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    commands:
      - rake code:verify

  - label: Build released library artifact
    timeout_in_minutes: 10
    key: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2020
    commands:
      - bundle install
      - 'bundle exec rake plugin:build:export'
    artifact_paths:
      - upm-package.zip
    retry:
      automatic:
        - exit_status: '*'
          limit: 1
    agents:
      queue: macos-14-unity-isolated
    concurrency: 1
    concurrency_group: "unity-license-server"
    concurrency_method: eager

  - label: Build size impact reporting
    depends_on: build-artifacts
    timeout_in_minutes: 10
    env:
      UNITY_PERFORMANCE_VERSION: *2021
    plugins:
      artifacts#v1.9.0:
        download:
          - upm-package.zip
    commands:
      - features/scripts/do_size_test.sh

  - label: Append Unity 2021 Basic Pipeline
    agents:
      queue: macos
    timeout_in_minutes: 2
    commands:
      - buildkite-agent pipeline upload .buildkite/unity.2021.yml

  - label: Conditionally trigger full set of tests
    agents:
      queue: macos
    timeout_in_minutes: 2
    commands:
      - sh -c .buildkite/pipeline_trigger.sh
