aliases:
  - &2021 "2021.3.45f1"

agents:
  queue: macos-14-isolated

steps:
  - group: ":hammer: Build Unity 2021 Test Fixtures"
    steps:
      - label: ':webgl: Build webgl DEV test fixture for Unity 2021'
        timeout_in_minutes: 15
        key: build-webgl-dev-fixture-2021
        depends_on: build-artifacts
        env:
          UNITY_PERFORMANCE_VERSION: *2021
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/mazerunner/mazerunner_webgl_dev_2021.zip
              - features/fixtures/build_webgl.log
        commands:
          - bundle install
          - 'rake test:webgl:build_dev'
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':windows: Build Windows DEV test fixture for Unity 2021'
        timeout_in_minutes: 30
        key: build-windows-dev-fixture-2021
        depends_on: build-artifacts
        agents:
          queue: windows-unity-wsl
        env:
          UNITY_PERFORMANCE_VERSION: *2021
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/mazerunner/build/Windows-dev-2021.zip
              - features/fixtures/build_windows.log
        commands:
          - features/scripts/import_package.sh --windows
          - features/scripts/build_windows.sh dev
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':macos: Build macos DEV test fixture for Unity 2021'
        timeout_in_minutes: 10
        key: build-macos-dev-fixture-2021
        depends_on: build-artifacts
        env:
          UNITY_PERFORMANCE_VERSION: *2021
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/mazerunner/mazerunner_macos_dev_2021.zip
              - features/fixtures/build_macos.log
        commands:
          - bundle install
          - 'rake test:macos:build_dev'
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':ios: Generate Xcode DEV project - Unity 2021'
        timeout_in_minutes: 10
        key: generate-dev-fixture-project-2021
        depends_on: build-artifacts
        env:
          UNITY_PERFORMANCE_VERSION: *2021
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/generateXcodeProject.log
              - dev_project_2021.tgz
        commands:
          - bundle install
          - 'rake test:ios:generate_xcode_dev'
          - tar -zvcf dev_project_2021.tgz features/fixtures/mazerunner/mazerunner_dev_xcode
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':ios: Build iOS DEV test fixture for Unity 2021'
        agents:
          queue: macos-14-isolated
        timeout_in_minutes: 10
        key: build-ios-dev-fixture-2021
        depends_on: generate-dev-fixture-project-2021
        env:
          UNITY_PERFORMANCE_VERSION: *2021
        plugins:
          'artifacts#v1.9.0':
            download:
              - dev_project_2021.tgz
            upload:
              - features/fixtures/mazerunner/mazerunner_dev_2021.ipa
              - features/fixtures/unity.log
        commands:
          - bundle install
          - tar -zxf dev_project_2021.tgz features/fixtures/mazerunner
          - 'rake test:ios:build_xcode_dev'
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

  - group: ":test_tube: E2E Tests Unity 2021"
    steps:
      - label: Run WebGL DEV e2e tests for Unity 2021
        agents:
          queue: macos-14-isolated
        timeout_in_minutes: 20
        depends_on: build-webgl-dev-fixture-2021
        env:
          UNITY_PERFORMANCE_VERSION: *2021
        plugins:
          'artifacts#v1.5.0':
            download:
              - features/fixtures/mazerunner/mazerunner_webgl_dev_2021.zip
            upload:
              - maze_output/**/*
              - '*-mazerunner.log'
              - 'clear_cache.log'
              - maze_output/metrics.csv
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        commands:
          - features/scripts/run-webgl-ci-tests.sh dev

      - label: Run Windows DEV e2e tests for Unity 2021
        timeout_in_minutes: 60
        depends_on: build-windows-dev-fixture-2021
        agents:
          queue: windows-unity-wsl
        env:
          UNITY_PERFORMANCE_VERSION: *2021
        plugins:
          'artifacts#v1.5.0':
            download:
              - features/fixtures/mazerunner/build/Windows-dev-2021.zip
            upload:
              - maze_output/**/*
              - '*-mazerunner.log'
              - 'clear_cache.log'
              - maze_output/metrics.csv
        commands:
          - features/scripts/run-windows-ci-tests.sh dev

      - label: ':android: Build Android Dev test fixture for Unity 2021'
        timeout_in_minutes: 10
        key: build-android-dev-fixture-2021
        depends_on: build-artifacts
        env:
          UNITY_PERFORMANCE_VERSION: *2021
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/mazerunner/mazerunner-dev_2021.apk
              - features/fixtures/import_package.log
              - features/fixtures/build_android_dev.log
        commands:
          - bundle install
          - 'rake test:android:build_dev'
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: Run MacOS DEV e2e tests for Unity 2021
        agents:
          queue: macos-14-isolated
        timeout_in_minutes: 30
        depends_on: build-macos-dev-fixture-2021
        env:
          UNITY_PERFORMANCE_VERSION: *2021
        plugins:
          'artifacts#v1.5.0':
            download:
              - features/fixtures/mazerunner/mazerunner_macos_dev_2021.zip
            upload:
              - maze_output/**/*
              - '*-mazerunner.log'
              - 'clear_cache.log'
              - maze_output/metrics.csv
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        commands:
          - features/scripts/run-macos-ci-tests.sh dev

      - label: ':bitbar: Run Android DEV e2e tests for Unity 2021'
        timeout_in_minutes: 60
        depends_on: build-android-dev-fixture-2021
        agents:
          queue: opensource
        plugins:
          'artifacts#v1.9.0':
            download:
              - features/fixtures/mazerunner/mazerunner-dev_2021.apk
            upload:
              - maze_output/**/*
          'docker-compose#v4.8.0':
            pull: maze-runner
            run: maze-runner
            service-ports: true
            command:
              - '--app=/app/features/fixtures/mazerunner/mazerunner-dev_2021.apk'
              - '--farm=bb'
              - '--device=ANDROID_9|ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13'
              - '--appium-version=1.22'
              - '--no-tunnel'
              - '--aws-public-ip'
              - '--fail-fast'
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar
        concurrency_method: eager

      - label: ':bitbar: Run iOS DEV e2e tests for Unity 2021'
        timeout_in_minutes: 60
        depends_on: build-ios-dev-fixture-2021
        agents:
          queue: opensource
        plugins:
          'artifacts#v1.9.0':
            download:
              - features/fixtures/mazerunner/mazerunner_dev_2021.ipa
            upload:
              - maze_output/**/*
          'docker-compose#v4.8.0':
            pull: maze-runner
            run: maze-runner
            service-ports: true
            command:
              - '--app=/app/features/fixtures/mazerunner/mazerunner_dev_2021.ipa'
              - '--farm=bb'
              - '--device=IOS_15'
              - '--no-tunnel'
              - '--aws-public-ip'
              - '--fail-fast'
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar
        concurrency_method: eager
