aliases:
  - &2020 "2020.3.48f1"

agents:
  queue: macos-14

steps:
  - label: Build released library artifact
    timeout_in_minutes: 30
    key: build-artifacts
    env:
      UNITY_PERFORMANCE_VERSION: *2020
    commands:
      - bundle install
      - 'bundle exec rake plugin:build:export'
    artifact_paths:
      - upm-package.zip
    retry:
      automatic:
        - exit_status: '*'
          limit: 1
