aliases:
  - &2020 "2020.3.48f1"

agents:
  queue: macos-15-isolated

steps:
  - group: ":hammer: Build Unity 2020 Test Fixtures"
    steps:
      - label: ':macos: Build macos test fixture for Unity 2020'
        timeout_in_minutes: 30
        key: build-macos-fixture-2020
        depends_on: build-artifacts
        agents:
          queue: macos-14
        env:
          XCODE_VERSION: 15.3.0
          UNITY_PERFORMANCE_VERSION: *2020
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/mazerunner/mazerunner_macos_2020.zip
              - features/fixtures/build_macos.log
        commands:
          - bundle install
          - 'rake test:macos:build'
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':windows: Build Windows test fixture for Unity 2020'
        timeout_in_minutes: 30
        key: build-windows-fixture-2020
        depends_on: build-artifacts
        agents:
          queue: windows-unity-wsl
        env:
          UNITY_PERFORMANCE_VERSION: *2020
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/mazerunner/build/Windows-2020.zip
              - features/fixtures/build_windows.log
        commands:
          - features/scripts/import_package.sh --windows
          - features/scripts/build_windows.sh release
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':android: Build Android test fixture for Unity 2020'
        timeout_in_minutes: 30
        key: build-android-fixture-2020
        depends_on: build-artifacts
        env:
          UNITY_PERFORMANCE_VERSION: *2020
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/mazerunner/mazerunner_2020.apk
              - features/fixtures/import_package.log
              - features/fixtures/build_android.log
        commands:
          - bundle install
          - 'rake test:android:build'
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':ios: Generate Xcode project - Unity 2020'
        timeout_in_minutes: 30
        key: generate-fixture-project-2020
        depends_on: build-artifacts
        env:
          UNITY_PERFORMANCE_VERSION: *2020
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/generateXcodeProject.log
              - project_2020.tgz
        commands:
          - bundle install
          - 'rake test:ios:generate_xcode'
          - tar -zvcf project_2020.tgz features/fixtures/mazerunner/mazerunner_xcode
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':ios: Build iOS test fixture for Unity 2020'
        timeout_in_minutes: 10
        key: build-ios-fixture-2020
        depends_on: generate-fixture-project-2020
        agents:
          queue: macos-14-isolated
        env:
          XCODE_VERSION: 15.3.0
          UNITY_PERFORMANCE_VERSION: *2020
        plugins:
          'artifacts#v1.9.0':
            download:
              - project_2020.tgz
            upload:
              - features/fixtures/mazerunner/mazerunner_2020.ipa
              - features/fixtures/unity.log
        commands:
          - bundle install
          - tar -zxf project_2020.tgz features/fixtures/mazerunner
          - 'rake test:ios:build_xcode'
        retry:
          automatic:
            - exit_status: '*'
              limit: 1
