aliases:
  - &2022 "2022.3.61f1"

agents:
  queue: macos-14

steps:
  - group: ":hammer: Build Unity 2022 Test Fixtures"
    steps:
      - label: ':macos: Build macos test fixture for Unity 2022'
        timeout_in_minutes: 20
        key: build-macos-fixture-2022
        depends_on: build-artifacts
        env:
          UNITY_PERFORMANCE_VERSION: *2022
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/mazerunner/mazerunner_macos_2022.zip
              - features/fixtures/build_macos.log
        commands:
          - bundle install
          - 'rake test:macos:build'
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':windows: Build Windows test fixture for Unity 2022'
        timeout_in_minutes: 30
        key: build-windows-fixture-2022
        depends_on: build-artifacts
        agents:
          queue: windows-unity-wsl
        env:
          UNITY_PERFORMANCE_VERSION: *2022
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/mazerunner/build/Windows-2022.zip
              - features/fixtures/build_windows.log
        commands:
          - features/scripts/import_package.sh --windows
          - features/scripts/build_windows.sh release
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':android: Build Android test fixture for Unity 2022'
        timeout_in_minutes: 10
        key: build-android-fixture-2022
        depends_on: build-artifacts
        env:
          UNITY_PERFORMANCE_VERSION: *2022
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/mazerunner/mazerunner_2022.apk
              - features/fixtures/import_package.log
              - features/fixtures/build_android.log
        commands:
          - bundle install
          - 'rake test:android:build'
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':ios: Generate Xcode project - Unity 2022'
        timeout_in_minutes: 10
        key: generate-fixture-project-2022
        depends_on: build-artifacts
        env:
          UNITY_PERFORMANCE_VERSION: *2022
        plugins:
          'artifacts#v1.9.0':
            download:
              - upm-package.zip
            upload:
              - features/fixtures/generateXcodeProject.log
              - project_2022.tgz
        commands:
          - bundle install
          - 'rake test:ios:generate_xcode'
          - tar -zvcf project_2022.tgz features/fixtures/mazerunner/mazerunner_xcode
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

      - label: ':ios: Build iOS test fixture for Unity 2022'
        timeout_in_minutes: 10
        key: build-ios-fixture-2022
        depends_on: generate-fixture-project-2022
        env:
          XCODE_VERSION: 15.3.0
          UNITY_PERFORMANCE_VERSION: *2022
        plugins:
          'artifacts#v1.9.0':
            download:
              - project_2022.tgz
            upload:
              - features/fixtures/mazerunner/mazerunner_2022.ipa
              - features/fixtures/unity.log
        commands:
          - bundle install
          - tar -zxf project_2022.tgz features/fixtures/mazerunner
          - 'rake test:ios:build_xcode'
        retry:
          automatic:
            - exit_status: '*'
              limit: 1

  - group: ":test_tube: E2E Tests Unity 2022"
    steps:
      - label: Run MacOS e2e tests for Unity 2022
        timeout_in_minutes: 30
        depends_on: build-macos-fixture-2022
        env:
          UNITY_PERFORMANCE_VERSION: *2022
        plugins:
          'artifacts#v1.9.0':
            download:
              - features/fixtures/mazerunner/mazerunner_macos_2022.zip
            upload:
              - maze_output/**/*
              - '*-mazerunner.log'
              - 'clear_cache.log'
              - maze_output/metrics.csv
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        commands:
          - features/scripts/run-macos-ci-tests.sh release

      - label: Run Windows e2e tests for Unity 2022
        timeout_in_minutes: 60
        depends_on: build-windows-fixture-2022
        agents:
          queue: windows-unity-wsl
        env:
          UNITY_PERFORMANCE_VERSION: *2022
        plugins:
          'artifacts#v1.5.0':
            download:
              - features/fixtures/mazerunner/build/Windows-2022.zip
            upload:
              - maze_output/**/*
              - '*-mazerunner.log'
              - 'clear_cache.log'
              - maze_output/metrics.csv
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        commands:
          - features/scripts/run-windows-ci-tests.sh release

      - label: ':bitbar: Run Android e2e tests for Unity 2022'
        timeout_in_minutes: 60
        depends_on: build-android-fixture-2022
        agents:
          queue: opensource
        plugins:
          'artifacts#v1.9.0':
            download:
              - features/fixtures/mazerunner/mazerunner_2022.apk
            upload:
              - maze_output/**/*
          'docker-compose#v4.8.0':
            pull: maze-runner
            run: maze-runner
            service-ports: true
            command:
              - '--app=/app/features/fixtures/mazerunner/mazerunner_2022.apk'
              - '--farm=bb'
              - '--device=ANDROID_9|ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13'
              - '--appium-version=1.22'
              - '--no-tunnel'
              - '--aws-public-ip'
              - '--fail-fast'
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar
        concurrency_method: eager

      - label: ':bitbar: Run iOS e2e tests for Unity 2022'
        timeout_in_minutes: 60
        depends_on: build-ios-fixture-2022
        agents:
          queue: opensource
        plugins:
          'artifacts#v1.9.0':
            download:
              - features/fixtures/mazerunner/mazerunner_2022.ipa
            upload:
              - maze_output/**/*
          'docker-compose#v4.8.0':
            pull: maze-runner
            run: maze-runner
            service-ports: true
            command:
              - '--app=/app/features/fixtures/mazerunner/mazerunner_2022.ipa'
              - '--farm=bb'
              - '--device=IOS_15'
              - '--no-tunnel'
              - '--aws-public-ip'
              - '--fail-fast'
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar
        concurrency_method: eager
